/** Inline SVG QR. The payload is generated by our own API, never user HTML. */
export default function QrCode({
  svg,
  label,
}: {
  svg: string;
  label: string;
}) {
  return (
    <div
      role="img"
      aria-label={label}
      className="mx-auto aspect-square w-52 overflow-hidden rounded-lg bg-white p-2 [&_svg]:h-full [&_svg]:w-full"
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
